services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Zeroseven\PagebasedBlog\:
        resource: '../Classes/*'

    Zeroseven\PagebasedBlog\EventListener\ExtendStructuredDataEvent:
        tags:
            -   name: event.listener
                identifier: 'pagebased_blog/extend-structured-data'
                event: Zeroseven\Pagebased\Event\StructuredDataEvent
